# Generated by Django 4.2.4 on 2023-08-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='Funcionario',
        ),
    ]
