# Generated by Django 4.2.4 on 2023-08-27 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_alter_registroponto_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
